### PR TITLE
Reformat test structure and imports

### PR DESCRIPTION
**Pull request by TylerYep**
Hi, I was interested in using this project, but ran into some issues with pip installing the package. I ended up renovating the project to fit my needs, and thought there was a chance you might be interested in using the changes.

Please feel free to take these changes or throw them away, I'm mainly just leaving this PR here as a suggestion of possible improvements! 

Changes included:
- Run `isort .`
- Run `black .`
- Rename `didyoumean` files to make imports easier
- Add a separate `tests/` folder to avoid mixing source files with test files
- Resolve several deprecation warnings that are raised when running `pytest`

### CODE REVIEW

**Comment by SylvainDe** [comment]
Thank you so much for your pull request!
I remember that I struggled trying to make this installable with pip for a very limited success ( https://github.com/SylvainDe/DidYouMean-Python/issues/3 ).

I'll have a look at the details and integrate it as soon as possible.

**Review by SylvainDe — CHANGES_REQUESTED** [review]
Thank you so much for the hard work you've put inthis contribution!

I have not gone through the whole review yet.

My first concern would be to ensure that the CI runs smoothly on all Python versions.
Currently, the pre-checks are failing because of the line length - the best option is to change the pycodestyle limit in the travis configuration.
Also, I suspect other tests would fail at runtime (at least on the older Python versions)

If you decide to spend more time on this, I would appreciate if things could be split into pull-requests with a somehow clearer scope. For instance, one for black (and typo), one for the reorganisation, etc. If you can't be bothered, that's fine as well.

Let me know if there's anything I may help you with

All the best!

**Comment by SylvainDe** [comment]
Note: I don't know why this does not appear more explicitly here but you can find the Travis runs for your Pull Request here: https://travis-ci.org/github/SylvainDe/DidYouMean-Python/builds/730786103 .

**Comment by TylerYep** [comment]
Are you dedicated to supporting Python 2.6 at this point? All versions of up to Python 3.5 have reached end-of-life by now (https://endoflife.date/python), so it seems wise to move along with this trend - especially if this project is not currently used by many people yet.

It would be pretty easy to split this into multiple changes - I can do it sometime this week. Thanks for reviewing the changes!

**Comment by SylvainDe** [comment]
This looks great! Thanks for the additional work you've gone through.

Unfortunately, I can see that the CI is failing - https://travis-ci.org/github/SylvainDe/DidYouMean-Python/pull_requests . Would you have any idea about what happened ?

As for the support for older Python version, I'd rather keep it until it does bring a lot more troubles while moving forward. If it is only for DeprecationWarning, I'd rather add a few wrappers around the unit-test methods to ensure that everything works smoothly in all cases.

**Comment by SylvainDe** [comment]
Hello @TylerYep , I've performed a few changes which will unfortunately lead to merge issues.
On the positive side: the DeprecationWarnings are now fixed and I've removed a few pep8 errors so that Black can be used safely.

To you mind resubmitting your code organisation PR ? (If you want, I can perform it myself based on the work you've done and try to give you the proper attribution). Similarly, I can perform the call to Black in a different commit if you want.

Please let me know how you want to  handle these and thanks for your work!

**Comment by TylerYep** [comment]
Resubmitted the PR. I can go ahead and create the PR for the black formatting, but could you fix the travis CI integration first?
I believe you just need to:
- Add the Travis-CI app in the Github Marketplace
- Add the DidYouMean project to TravisCI (I believe this is already done)
- Remove the scrutinizer app from this project

As a side note, I would also really recommend upgrading to a newer toolchain for linting + testing. I believe the more common standard now is `pytest + flake8` instead of `unittest + pep8/pycodestyle/pyflakes`.

**Comment by SylvainDe** [comment]
Thanks for all the suggestions ! It looks like I have not followed the latest trends on a few aspects indeed.
I've disabled scrutinizer for all PRs.
As for Travis, a few things changed (apps, migration from org to com) and I did not quite manage to make it work yet. I'll try again later on.

**Pull request closed without merging**
